
    <!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 Box.gltf
-->




    <script>
				
	
	
  
        import { T } from '@threlte/core'
        import { useGltf } from '@threlte/extras'
	

        let {
					fallback,
          error,
          children,
          ref = $bindable(),
          ...props
        } = $props()

				

				

        

        const gltf = useGltf('gltf/Box.gltf')

    
    </script>

		<T.Group bind:ref dispose={false} {...props}>
			{#await gltf}
        {@render fallback?.()}
			{:then gltf}
				<T.Mesh geometry={gltf.nodes.Cube_1.geometry} material={gltf.materials.BoxTop} />
<T.Mesh geometry={gltf.nodes.Cube_2.geometry} material={gltf.materials.BoxSide1} />
<T.Mesh geometry={gltf.nodes.Cube_3.geometry} material={gltf.materials.BoxSide2} />
<T.Mesh geometry={gltf.nodes.Cube_4.geometry} material={gltf.materials.BoxBottom} />

			{:catch err}
        {@render error?.({ error: err })}
			{/await}

      {@render children?.({ ref })}
		</T.Group>
	